### ISSUE TITLE
Fails to create JAR with Gradle api dependencies

### ISSUE THREAD

**Issue by mjpt777** [johnrengelman/shadow#424]
I get the following failure when trying to build Gradle api dependencies with 'java-library'.

```
> Task :sbe-all:shadowJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sbe-all:shadowJar'.
> path may not be null or empty string. path='null'
```

### Shadow Version
4.0.2.

### Gradle Version
4.10.1.

### Expected Behavior
Successfully create a JAR with shaded api dependencies.

### Actual Behavior
Build fails.

### Gradle Build Script(s)

Apply the attached patch to the following file and build.

https://github.com/real-logic/simple-binary-encoding/blob/master/build.gradle

[java-library.zip](https://github.com/johnrengelman/shadow/files/2558666/java-library.zip)

**Comment by JamesXNelson** [comment]
I've debugged this down to "shadow borks when using task output dependencies anywhere on runtime classpath".  If the dependency is a SelfResolvingDependency, the logic in com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker#getApiJarsFromProject is wrong.

Needs either a null check and throw there, where it actually helps to know what is causing null, or needs to handle (or ignore, with really loud warnings, maybe) the SelfResolvingDependency type.

**Comment by JamesXNelson** [comment]
This issue should already be fixed w/ the merged code above.

**Comment by jrodbx** [comment]
This issue still exists in 4.0.4 and Gradle 4.10.2.  Downgrading to 4.0.1 solved the problem for me.  @johnrengelman, should I file another issue or shall this ticket be reopened?

**Comment by JamesXNelson** [comment]
If the original test case fails, then reopen.  If not, new issue.

**Comment by JamesXNelson** [comment]
also, try to use gradle 4.10.3.  Not sure if that's EOL for the 4.X line or not, but it's worth ruling out "anything except the newest patch version of the previous major version".
